### ISSUE TITLE
Spanish translations for Intro To Jupyter Notebooks (Python)

### ISSUE THREAD

**Issue by alfredodeza** [microsoft/workshop-library#109]
This issue is for the short workshop on [Introduction To Jupyter Notebooks in Python](https://github.com/microsoft/workshop-library/tree/main/short/intro-jupyter-notebooks-python) being translated into Spanish

The structure of the translation should follow other translations like https://github.com/microsoft/workshop-library/tree/main/full/intro-nlp-tensorflow/translations

**Comment by alfredodeza** [comment]
Thanks so much for the help @aleepsy

**Comment by alfredodeza** [comment]
@aleepsy me parece que este taller ya se hizo via https://github.com/microsoft/workshop-library/pull/91 ! Lo siento mucho! 

Me avisas si hay algun otro taller que quieres traducir

**Comment by aleepsy** [comment]
¡Claro que sí! @alfredodeza si también tienes uno en mente que no haya sido traducido antes, con mucho gusto. 
Gracias ☺️
