### ISSUE TITLE
Spanish translations for Build an App without Using any Code with Microsoft Power Platform

### ISSUE THREAD

**Issue by abrilurena** [microsoft/workshop-library#114]
This issue is for the short workshop on [Build an App without Using any Code with Microsoft Power Platform
](https://github.com/microsoft/workshop-library/blob/main/full/power-platform-canvas-app/README.md) being translated into Spanish

The structure of the translation should follow other translations like https://github.com/microsoft/workshop-library/tree/main/full/intro-nlp-tensorflow/translations

**Comment by aleepsy** [comment]
> thanks to @aleepsy for taking this one :D

Hello @abrilurena can you review please the Pull Request?
Greetings! :D
