### ISSUE TITLE
QA Testing for https://github.com/microsoft/workshop-library/blob/main/build-canvas-apps/README.md

### ISSUE THREAD

**Issue by jlooper** [microsoft/workshop-library#24]
Please 'adopt' a workshop for testing, and check off these tasks!

- [ ] All elements of the workshop are in place (README, workshop designer, solution if necessary, any images if necessary, slides, a call-to-action with a Learn module linked (usually in "Next Steps" area), a knowledge check (either in slides or directly linked to the workshop README) and an area to extend knowledge.
- [ ] The workshop can be done in its listed time frame
- [ ] Instructions are clear and well written
- [ ] The workshop is bug-free
- [ ] The workshop 'flows' well
- [ ] There are no stray auth keys or secrets embedded in the code

**Comment by CinnamonXI** [comment]
Hi @jlooper, I just audited this workshop, all seems well and all checkpoints met.
A few observations in the slide.
1. On page 22 has a play button, It doesn't seem to play any video, is it supposed to be there?
2. On page 37, the instruction on how to share the app, can it be divided into two pages? the font size is too small and when sharing screen it won't be easy to read by the presenter and attendees
3. Pages 39 and 41 have the same thing
4. On page 50, can the key takeaways tables be moved up close to the header. same thing for the textbox on page 51
5. Is page 54(last page) supposed to be totally empty?

**Comment by jlooper** [comment]
thank you @CinnamonXI I will edit the slides!

**Comment by jlooper** [comment]
fixed, thank you for the QA!
