### ISSUE TITLE
QA testing for https://github.com/microsoft/workshop-library/blob/main/flask-text-translator/README.md

### ISSUE THREAD

**Issue by jlooper** [microsoft/workshop-library#25]
- [ ] All elements of the workshop are in place (README, workshop designer, solution if necessary, any images if necessary, slides, a call-to-action with a Learn module linked (usually in "Next Steps" area), a knowledge check (either in slides or directly linked to the workshop README) and an area to extend knowledge.
- [ ] The workshop can be done in its listed time frame
- [ ] Instructions are clear and well written
- [ ] The workshop is bug-free
- [ ] The workshop 'flows' well

**Comment by jlooper** [comment]
Shekhinah discovered this issue - cc @GeekTrainer 
<img width="801" alt="Screen Shot 2022-02-10 at 3 17 42 PM" src="https://user-images.githubusercontent.com/1450004/153489605-f2fd4e06-a0e0-4a84-b55f-21373aaba348.png">

**Comment by GeekTrainer** [comment]
PR has been made, and will be merged momentarily. Going to close this now
