### ISSUE TITLE
QA testing for https://github.com/microsoft/workshop-library/blob/main/learn-github/README.md

### ISSUE THREAD

**Issue by jlooper** [microsoft/workshop-library#29]
- [ ] All elements of the workshop are in place (README, workshop designer, solution if necessary, any images if necessary, slides, a call-to-action with a Learn module linked (usually in "Next Steps" area), a knowledge check (either in slides or directly linked to the workshop README) and an area to extend knowledge.
- [ ] The workshop can be done in its listed time frame
- [ ] Instructions are clear and well written
- [ ] The workshop is bug-free
- [ ] The workshop 'flows' well

**Comment by sheki018** [comment]
- [x] All elements of the workshop are in place (README, workshop designer, solution if necessary, any images if necessary, slides, a call-to-action with a Learn module linked (usually in "Next Steps" area), a knowledge check (either in slides or directly linked to the workshop README) and an area to extend knowledge.
 - [x]  The workshop can be done in its listed time frame
 - [x]  Instructions are clear and well written
 - [x]  The workshop is bug-free
 - [x]  The workshop 'flows' well
