### ISSUE TITLE
GitHub.dev blocker - merge and PR disabled

### ISSUE THREAD

**Issue by jlooper** [microsoft/workshop-library#33]
Several folks have observed a problem with the steps of the GitHub.dev workshop https://github.com/microsoft/workshop-library/tree/main/learn-github - 

We are unable to complete the merging of the branch and raising a PR to our main branch using GitHub.dev. The error seems to indicate that there is no upstream branch, which is wrong.

This was captured by our student ambassador tester: 
<img width="517" alt="Screen Shot 2022-02-08 at 12 13 20 PM" src="https://user-images.githubusercontent.com/1450004/153039685-045d6abb-333f-4ba6-9aeb-1d978384bdcb.png">

**Comment by bamurtaugh** [comment]
@joyceerhl Do you have thoughts on this?

**Comment by joyceerhl** [comment]
Investigating... This message is displayed by GHPRI: https://github.com/microsoft/vscode-pull-request-github/blob/48bb6db679042486573e8ab592e489c548815442/src/github/createPRViewProvider.ts#L315

cc @alexr00

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3309

**Comment by sheki018** [comment]
Sure! I'll test it and let you know asap.

**Comment by jlooper** [comment]
Closing! nice :)
