### ISSUE TITLE
QA for resume workshop (https://github.com/microsoft/workshop-library/tree/main/full/build-resume-website)

### ISSUE THREAD

**Issue by jlooper** [microsoft/workshop-library#44]
- [ ] All elements of the workshop are in place (README, workshop designer, solution if necessary, any images if necessary, slides, a call-to-action with a Learn module linked (usually in "Next Steps" area), a knowledge check (either in slides or directly linked to the workshop README) and an area to extend knowledge.
- [ ] The workshop can be done in its listed time frame
- [ ] Instructions are clear and well written
- [ ] The workshop is bug-free
- [ ] The workshop 'flows' well
- [ ] There are no stray auth keys or secrets embedded in the code

**Comment by jlooper** [comment]
missed this one! sorry @ornelladotcom

**Comment by CinnamonXI** [comment]
The observation I have is that there is no knowledge check and the next steps should be added to the readme as well. I have a resume on the web now ... hurray :)
I'd love to deliver this workshop, it was very easy to follow.

**Comment by jlooper** [comment]
Awesome!! do you want to propose some next steps that would be useful to you? We can add those right in.

**Comment by CinnamonXI** [comment]
It has the next steps on [this](https://github.com/microsoft/workshop-library/blob/main/full/build-resume-website/4-creating-website.md) page, I am just proposing that it should be added to the readme as well. I will come up with knowledge checks, it should be 3 questions, right? 
Apart from that, I think all is set.

**Comment by CinnamonXI** [comment]
Proposed knowledge checks

Q1: HTML stands for? 
a. Hypertext Markdown Language (ans)
b. Hypotext Markup Language
c. Hypertext Markup Language

Q2: Every HTML has ____ main tags and they are?
a. 3 (html, head, and body) (ans)
b. 3 (head, body, and tail)
c. 4 (html, head, body and tail)

Q3: CSS is used to set the following except 
a. tag (ans)
b. color 
c. font

**Comment by jlooper** [comment]
adding! (the answer to Q1 is c :))

**Comment by CinnamonXI** [comment]
OMG 😆 
I changed the options because I did want A to be the correct one 😅

**Comment by jlooper** [comment]
Got it :) thanks!!
