### ISSUE TITLE
QA for https://github.com/microsoft/workshop-library/blob/main/full/deep-learning-computer-vision/README.md

### ISSUE THREAD

**Issue by jlooper** [microsoft/workshop-library#54]
- [ ] All elements of the workshop are in place (README, workshop designer, solution if necessary, any images if necessary, slides, a call-to-action with a Learn module linked (usually in "Next Steps" area), a knowledge check (either in slides or directly linked to the workshop README) and an area to extend knowledge.
- [ ] The workshop can be done in its listed time frame
- [ ] Instructions are clear and well written
- [ ] The workshop is bug-free
- [ ] The workshop 'flows' well
- [ ] There are no stray auth keys or secrets embedded in the code

**Comment by CinnamonXI** [comment]
All elements are in place but the workshop will take more than an hour, I didn't find it easy to follow perhaps because I'm not in the Machine Learning space but, the workshop is definitely not to be done by someone who doesn't have knowledge of ML.

**Comment by CinnamonXI** [comment]
I was thinking if it is possible for you to add a row called experience level to the goals table, the author of the workshop will add if the workshop can be administered by beginners, intermediate or advanced.

**Comment by jlooper** [comment]
hi, there's a suite of emojis that gives the level - this one is more advanced, for sure!

**Comment by jlooper** [comment]
closing as I think we're ok with it!
