### ISSUE TITLE
Spanish translations for Intro to GitHub and GitHub Dev

### ISSUE THREAD

**Issue by alfredodeza** [microsoft/workshop-library#89]
This issue is for translating the [Intro to GitHub and GitHub Dev workshop](https://github.com/microsoft/workshop-library/blob/main/short/intro-github-dev/README.md) to Spanish.

**Comment by DaniMSix** [comment]
Hi @alfredodeza I finished translating the document 😃

**Comment by alfredodeza** [comment]
Thanks so much for your contribution @DaniMSix ! Great job
